server_url : 'http://your_server.example.com'
development_computer_url : 'http://localhost:3000/payments/ipn'

:via : :smtp
:via_options:
  :address : 0.0.0.1
  :openssl_verify_mode : none

polling_interval_seconds : '5.0'

poll_checking_interval_seconds : '3600.0'

sandbox_id : ['my_sandbox_id','my_sandbox_id_1']

computer_testing:
  'my_sandbox_id': false
  'my_sandbox_id_1': false

queue_map:
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~

last_poll_time :
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~

email_map :
  'my_sandbox_id': dmitri.ostapenko@gmail.com
  'my_sandbox_id_1': bob@example.com

poll_checker_instance :
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~