server_url : 'http://localhost:8810/'
development_computer_url : 'http://localhost:3000/payments/ipn'

polling_interval_seconds : '5.0'

poll_checking_interval_seconds : '.1'

no_polling_time_before_email : 3600

no_ipn_time_before_email : 600

sandbox_id : ['my_sandbox_id','my_sandbox_id_1']

developers_email : 'developers@hedgeye.com'

computer_testing:
  'my_sandbox_id': false
  'my_sandbox_id_1': false

queue_map:
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~

last_poll_time :
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~

email_map :
  'my_sandbox_id': developer@gmail.com
  'my_sandbox_id_1': bob@example.com

poll_checker_instance :
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~

ipn_reception_checker_instance :
  'my_sandbox_id': ~
  'my_sandbox_id_1': ~



